### PR TITLE
Add support for ctrl + click to open included file

### PR DESCRIPTION
**Pull request by sea1jxr**
Enable ctrl + click on an include file to open that file.

I had to update the engines and  vscode version to allow the usage of the LocationLink which allows the code to specify the range of definition origin, so it turns the correct part of the text into a link when the user ctrl + hover over it.   The new version works with VS instances from mid 2018, so should be ok.  Upgraded typescript to work with the new vscode types file.

image

### CODE REVIEW

**Comment by sea1jxr** [comment]
@alexrp @bricelam @awglyde @zbecknell Any thoughts on this change?

**Comment by awglyde** [comment]
Hey @sea1jxr! Thanks for the reach out - unfortunately I don't work with T4 anymore so don't have much of a take here! Seems like the feature would have been useful back when I was using it before though!

**Comment by bricelam** [comment]
I'll let @zbecknell comment on the implementation, but yeah, I like the feature!

**Comment by zbecknell** [comment]
I’ll try to get this published today or tomorrow. Sorry for the delay and
thank you for the contribution!

**Comment by sea1jxr** [comment]
@zbecknell I was considering adding a hover to the import path to say "open in file editor (ctrl + click)" like VSCode does in several places.  That should make this feature more discoverable.  Would you been open to that if I get time?

**Comment by zbecknell** [comment]
I've merged and published this @sea1jxr. Please do feel free to add any features you'd like. I've invited everyone here as contributors so you have the ability to merge at will. I need to set up a CI/CD pipeline but don't have time quite as of yet.

Thanks again for your contribution!

**Comment by sea1jxr** [comment]
@zbecknell sounds great happy to be a contributor.  I do appreciate a review of code on future submissions if you have time.  Also I believe I will still need your help with publishing. Correct?

**Comment by zbecknell** [comment]
Yes, right now I have to manually publish. For this PR I’ve already done
that as version 0.7.0.  Definitely don’t hesitate to ask for a review any
time, I just may take a while to respond depending on how work things are
going.

**Pull request merged**
